<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="user" ignored="0" name="Test" tests="8" failures="2" timestamp="2021-12-28T16:11:38 IST" time="0.339" errors="0">
  <testcase name="password" time="0.031" classname="com.testng.I_Retry_Analyser">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.01" classname="com.testng.I_Retry_Analyser">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.006" classname="com.testng.I_Retry_Analyser">
    <skipped/>
  </testcase> <!-- password -->
  <testcase name="password" time="0.011" classname="com.testng.I_Retry_Analyser">
    <failure type="java.lang.AssertionError" message="expected [VK@123] but found [vk@123]">
      <![CDATA[java.lang.AssertionError: expected [VK@123] but found [vk@123]
at com.testng.I_Retry_Analyser.password(I_Retry_Analyser.java:19)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- password -->
  <testcase name="username" time="0.007" classname="com.testng.I_Retry_Analyser">
    <skipped/>
  </testcase> <!-- username -->
  <testcase name="username" time="0.011" classname="com.testng.I_Retry_Analyser">
    <skipped/>
  </testcase> <!-- username -->
  <testcase name="username" time="0.005" classname="com.testng.I_Retry_Analyser">
    <skipped/>
  </testcase> <!-- username -->
  <testcase name="username" time="0.006" classname="com.testng.I_Retry_Analyser">
    <failure type="java.lang.AssertionError" message="expected [VIKEY] but found [Vikey]">
      <![CDATA[java.lang.AssertionError: expected [VIKEY] but found [Vikey]
at com.testng.I_Retry_Analyser.username(I_Retry_Analyser.java:12)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- username -->
</testsuite> <!-- Test -->
